name: 🚀 Release
on:
  release:
    types: [published]

concurrency:
  group: ${{ github.ref_name }}_${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  release:
    name: Release
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # 4.2.1
        with:
          role-to-assume: arn:aws:iam::119673406361:role/ecr-pull-push-fluidstack-role
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | \
            docker login 119673406361.dkr.ecr.us-east-2.amazonaws.com --username=AWS --password-stdin

      - name: Build Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: . # path to dockerfile, relative to repository root
          push: true
          load: true
          tags: |
            119673406361.dkr.ecr.us-east-2.amazonaws.com/fluidstack/container-usage:${{ github.event.release.tag_name }}
            119673406361.dkr.ecr.us-east-2.amazonaws.com/fluidstack/container-usage:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
